# Generated by Django 3.0 on 2019-12-11 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('working_from', models.TimeField()),
                ('working_to', models.TimeField()),
                ('average_delivery_time', models.IntegerField(default=0)),
                ('weekends', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('approximate_delivery', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'In progress'), (2, 'Delivered')], default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.Provider')),
            ],
            options={
                'ordering': ['-approximate_delivery'],
            },
        ),
    ]
