# Generated by Django 3.0 on 2019-12-11 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.Warehouse')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='ProductLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.IntegerField(default=100)),
                ('min_amount', models.IntegerField(default=10)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit', to='products.Product')),
            ],
            options={
                'order_with_respect_to': 'product',
            },
        ),
    ]
